// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibgfvsxzbeexsklplduz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZ2Z2c3h6YmVleHNrbHBsZHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMzMyMjUsImV4cCI6MjA1NjgwOTIyNX0.8aKzP7FpPTODGSOAkNCELzno04lufGPTzPhoz_IJgew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);